### ISSUE TITLE
Missing permission descriptions

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-devx-content#178]
These two permissions are not listed in the description files:
- [ ] SubjectRightsRequest.Read.All
- [ ] SubjectRightsRequest.ReadWrite.All

Blocking:
- Graph Explorer to ask for these permissions
- Raptor tests that require these permissions to execute

Relevant documentation:
https://docs.microsoft.com/en-us/graph/api/subjectrightsrequest-list?view=graph-rest-1.0&tabs=http

The permissions are also available in Azure Portal.

cc: @irvinesunday

**Comment by zengin** [comment]
Another one:
- [ ] OnlineMeetingArtifact.Read.All

**Comment by irvinesunday** [comment]
Hi @zengin the above mentioned permissions are now available in GE:


![MicrosoftTeams-image (27)](https://user-images.githubusercontent.com/40403681/151986170-01de978f-387c-4137-ba5a-7b450d8bb9b0.png)

![image](https://user-images.githubusercontent.com/40403681/151985916-2610f147-926c-441f-b371-91345b83ca83.png)

**Comment by zengin** [comment]
Thank you @irvinesunday, really appreciate the quick resolution.
